### ISSUE TITLE
Prompt to change to admin is confusing

### ISSUE THREAD

**Issue by xinwenfu** [ChrisM09/FrausDNS#6]
![VirtualBox_Windows 10 VM_03_10_2020_10_50_16](https://user-images.githubusercontent.com/69218457/94995017-56267d00-0569-11eb-8a79-a85a68bc17d3.png)

Really has no idea this dialog window means FrausDNS will use the admin priviledge. Can we explicitly notify users that FrausDNS is going to run as administrator?

No need to rush to fix issues. Please fix them when you have time! I'm just documenting issues I found

**Comment by ChrisM09** [comment]
Cannot customize the UAC prompt. Alternative way would be to create a separate launcher and start the executable as a process after a message box. Decided to not implement this to avoid confusion and other problems.
